sudo: required
language: node_js
node_js:
  - "8"

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"

env:
  - CXX=g++-4.8

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000 &

script:
  - meteor test-packages --driver-package practicalmeteor:mocha ../apinf-fiware
